GEMINI_API_KEY = "AIzaSyDhPUcjjcRQCyVowTifHsoxKsIaV2G55fg"
TWILIO_ACCOUNT_SID = "AC1be6ae28d832ac29874458c8a27a1eb7"
TWILIO_AUTH_TOKEN = "5d52edbf5710e0b09cec5ef177d5ddb8" 
TWILIO_WHATSAPP_NUMBER = "whatsapp:+12086827968"
YOUR_WHATSAPP_NUMBER = "whatsapp:+918849594887"
